
project_id = "wlguhfzutzlikoccispq"

[functions.generate-embeddings]
verify_jwt = false

[functions.rag-search]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false
