// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
const OPENAI_API_KEY = "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";
const SUPABASE_URL = "https://wlguhfzutzlikoccispq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsZ3VoZnp1dHpsaWtvY2Npc3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDc5MzEsImV4cCI6MjA2NDQ4MzkzMX0.RjgJynmpE1WJRmbMScstqfnw5frEtrkKpzA2J9z_IHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);